/*
 * South Park / Kill Kenny catalog for Lampa 3.x
 * v1.2.0
 *
 * Architecture:
 *   Lampa.Maker native UI -> catalog.json on GitHub Pages
 *
 * catalog.json is generated by GitHub Actions from public metadata pages.
 * The browser/TV client never needs to fetch kill-kenny HTML directly.
 */
(function () {
    'use strict';

    var PLUGIN_ID = 'sp_killkenny_v1';
    var COMPONENT = 'sp_killkenny_native';
    var VERSION = '1.2.0';
    var TITLE = 'Южный Парк';

    var SCRIPT_URL = (document.currentScript && document.currentScript.src) || '';
    var ASSET_BASE = SCRIPT_URL
        ? SCRIPT_URL.split('?')[0].replace(/[^/]+$/, '')
        : 'https://cloverdlae.github.io/sp-lampa/';

    var CATALOG_URLS = [
        ASSET_BASE + 'catalog.json?v=' + encodeURIComponent(VERSION),
        'https://raw.githubusercontent.com/cloverdlae/sp-lampa/main/catalog.json'
    ];

    /*
     * Known direct HLS rules supplied separately by the user.
     * Add only verified season rules here.
     */
    var STREAM_RULES = {
        10: {
            base: 'https://cdn.videozcdn.uk/video/killkenny/s10-mtv/',
            suffix: '.mp4/index.m3u8'
        },
        16: {
            base: 'https://cdn.videozcdn.uk/video/killkenny/s16-paramount/',
            suffix: '.mp4/index.m3u8'
        }
    };

    var catalogCache = null;

    var ICON =
        '<svg viewBox="0 0 24 24" width="34" height="34" fill="none" stroke="currentColor" stroke-width="2">' +
            '<rect x="3" y="4" width="18" height="16" rx="2"></rect>' +
            '<path d="M7 8h10M7 12h10M7 16h6"></path>' +
        '</svg>';

    function appDigital() {
        try {
            return Number(Lampa.Manifest.app_digital || 0);
        } catch (e) {
            return 0;
        }
    }

    function pad2(value) {
        value = parseInt(value, 10) || 0;
        return value < 10 ? ('0' + value) : String(value);
    }

    function streamUrl(season, episode) {
        var rule = STREAM_RULES[parseInt(season, 10)];

        if (!rule) return '';

        return rule.base + pad2(episode) + rule.suffix;
    }

    function fallbackCatalog() {
        var seasons = {};

        for (var i = 1; i <= 28; i++) {
            seasons[String(i)] = {
                season: i,
                title: i + ' сезон',
                episodes: []
            };
        }

        return {
            version: 1,
            source: 'kill-kenny.com',
            updated_at: null,
            seasons: seasons
        };
    }

    function parseCatalog(text) {
        var data = typeof text === 'string' ? JSON.parse(text) : text;

        if (!data || typeof data !== 'object') throw new Error('bad catalog');
        if (!data.seasons || typeof data.seasons !== 'object') throw new Error('no seasons');

        return data;
    }

    function loadText(url, success, fail) {
        if (typeof fetch === 'function') {
            fetch(url, {
                method: 'GET',
                mode: 'cors',
                cache: 'no-store'
            })
            .then(function (response) {
                if (!response.ok) throw new Error('HTTP ' + response.status);
                return response.text();
            })
            .then(success)
            .catch(function () {
                requestFallback(url, success, fail);
            });

            return;
        }

        requestFallback(url, success, fail);
    }

    function requestFallback(url, success, fail) {
        try {
            var network = Lampa.Network
                ? new Lampa.Network()
                : new Lampa.Reguest();

            network.silent(
                url,
                function (data) {
                    success(typeof data === 'string' ? data : String(data || ''));
                },
                fail,
                false,
                {
                    dataType: 'text',
                    cache: {
                        life: 5
                    }
                }
            );
        } catch (e) {
            fail(e);
        }
    }

    function loadCatalog(done) {
        if (catalogCache) {
            done(catalogCache, false);
            return;
        }

        var index = 0;

        function next() {
            if (index >= CATALOG_URLS.length) {
                catalogCache = fallbackCatalog();
                done(catalogCache, true);
                return;
            }

            var url = CATALOG_URLS[index++];

            loadText(
                url,
                function (text) {
                    try {
                        catalogCache = parseCatalog(text);
                        done(catalogCache, false);
                    } catch (e) {
                        next();
                    }
                },
                next
            );
        }

        next();
    }

    function seasonRecord(catalog, season) {
        return catalog &&
            catalog.seasons &&
            (catalog.seasons[String(season)] || catalog.seasons[season]);
    }

    function firstPoster(seasonData) {
        if (!seasonData || !seasonData.episodes) return '';

        for (var i = 0; i < seasonData.episodes.length; i++) {
            if (seasonData.episodes[i].poster) return seasonData.episodes[i].poster;
        }

        return '';
    }

    function chunks(items, size) {
        var out = [];

        for (var i = 0; i < items.length; i += size) {
            out.push(items.slice(i, i + size));
        }

        return out;
    }

    function seasonCard(seasonData) {
        var season = parseInt(seasonData.season, 10);
        var count = (seasonData.episodes || []).length;
        var cardData = {
            title: season + ' сезон',
            name: season + ' сезон',
            original_name: count ? (count + ' серий • OK — открыть') : 'OK — открыть сезон',
            overview: count
                ? ('Сезон ' + season + ' • ' + count + ' серий')
                : ('Сезон ' + season),
            img: firstPoster(seasonData),
            kk_type: 'season',
            kk_season: season
        };

        cardData.params = {
            style: {
                name: 'wide'
            },
            emit: {
                onFocus: function () {
                    updateBackground(cardData);
                },
                onlyEnter: function () {
                    pushSeason(season);
                }
            }
        };

        return cardData;
    }

    function episodeCard(episode) {
        var playable = !!streamUrl(episode.season, episode.episode);

        var cardData = {
            title: episode.title || (episode.episode + ' серия'),
            name: episode.title || (episode.episode + ' серия'),
            original_name:
                'Сезон ' + episode.season +
                ' • Серия ' + episode.episode +
                (playable ? ' • ▶ OK — смотреть' : ' • OK — действия'),
            overview: episode.description || '',
            img: episode.poster || '',
            kk_type: 'episode',
            kk_episode: episode
        };

        cardData.params = {
            style: {
                name: 'wide'
            },
            emit: {
                onFocus: function () {
                    updateBackground(cardData);
                },
                onlyEnter: function () {
                    openEpisodeActions(episode);
                }
            }
        };

        return cardData;
    }

    function escapeHtml(value) {
        if (Lampa.Utils && Lampa.Utils.escape) {
            return Lampa.Utils.escape(String(value || ''));
        }

        return String(value || '')
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;');
    }

    function modalHtml(episode, stream) {
        var description = episode.description || 'Описание для этой серии пока отсутствует в catalog.json.';
        var poster = episode.poster || '';

        var html =
            '<div class="kkv1-info" style="padding:.4em .2em 1em;line-height:1.45">' +
                (poster
                    ? '<div style="margin-bottom:1em"><img src="' + escapeHtml(poster) + '" style="max-width:26em;max-height:14em;border-radius:.6em;object-fit:cover"></div>'
                    : '') +
                '<div style="font-size:1.1em;opacity:.86">' + escapeHtml(description) + '</div>' +
                '<div style="margin-top:1em;opacity:.55;font-size:.86em">' +
                    'Сезон ' + episode.season + ' • Серия ' + episode.episode +
                    (stream ? ' • HLS доступен' : ' • поток пока не настроен') +
                '</div>' +
            '</div>';

        return $(html);
    }

    function playEpisode(episode) {
        var url = streamUrl(episode.season, episode.episode);

        if (!url) {
            Lampa.Noty.show(
                'Для ' + episode.season + ' сезона поток пока не настроен'
            );
            return;
        }

        var all = [];
        var season = seasonRecord(catalogCache, episode.season);

        if (season && season.episodes) {
            season.episodes.forEach(function (item) {
                var itemUrl = streamUrl(item.season, item.episode);

                if (itemUrl) {
                    all.push({
                        title: item.title || (item.episode + ' серия'),
                        url: itemUrl,
                        season: item.season,
                        episode: item.episode,
                        img: item.poster || ''
                    });
                }
            });
        }

        var current = {
            title: episode.title || (episode.episode + ' серия'),
            url: url,
            season: episode.season,
            episode: episode.episode,
            img: episode.poster || ''
        };

        try {
            Lampa.Storage.set('kkv1_last', {
                season: episode.season,
                episode: episode.episode,
                title: current.title
            });
        } catch (e) {}

        Lampa.Player.play(current);
        Lampa.Player.playlist(all.length ? all : [current]);
    }

    function showEpisodeInfo(episode, controller) {
        var stream = streamUrl(episode.season, episode.episode);

        Lampa.Modal.open({
            title: episode.title || (episode.episode + ' серия'),
            html: modalHtml(episode, stream),
            size: 'medium',
            onBack: function () {
                if (controller) {
                    setTimeout(function () {
                        Lampa.Controller.toggle(controller);
                    }, 0);
                }
            }
        });
    }

    function openEpisodeActions(episode) {
        var controller = '';
        var stream = streamUrl(episode.season, episode.episode);
        var items = [];

        try {
            controller = Lampa.Controller.enabled().name;
        } catch (e) {
            controller = 'content';
        }

        if (stream) {
            items.push({
                title: '▶ Смотреть',
                action: 'play'
            });
        } else {
            items.push({
                title: 'Поток для ' + episode.season + ' сезона пока не настроен',
                action: 'missing'
            });
        }

        items.push({
            title: 'О серии',
            action: 'info'
        });

        Lampa.Select.show({
            title: episode.title || (episode.episode + ' серия'),
            items: items,

            onSelect: function (item) {
                if (!item) return;

                if (item.action === 'play') {
                    Lampa.Select.close();

                    setTimeout(function () {
                        playEpisode(episode);
                    }, 120);

                    return;
                }

                if (item.action === 'info') {
                    Lampa.Select.close();

                    setTimeout(function () {
                        showEpisodeInfo(episode, controller);
                    }, 120);

                    return;
                }

                if (item.action === 'missing') {
                    Lampa.Noty.show(
                        'Для ' + episode.season + ' сезона HLS пока не добавлен'
                    );
                }
            },

            onBack: function () {
                if (controller) {
                    setTimeout(function () {
                        Lampa.Controller.toggle(controller);
                    }, 0);
                }
            }
        });
    }

    function pushSeason(season) {
        Lampa.Activity.push({
            component: COMPONENT,
            title: season + ' сезон',
            kk_mode: 'episodes',
            kk_season: season,
            page: 1
        });
    }

    function updateBackground(data) {
        if (!data || !data.img) return;

        try {
            Lampa.Background.change(data.img);
        } catch (e) {}
    }

    function buildSeasonLines(catalog) {
        var items = [];

        Object.keys(catalog.seasons || {})
            .map(function (key) {
                return seasonRecord(catalog, parseInt(key, 10));
            })
            .filter(Boolean)
            .sort(function (a, b) {
                return parseInt(a.season, 10) - parseInt(b.season, 10);
            })
            .forEach(function (seasonData) {
                items.push(seasonCard(seasonData));
            });

        var groups = chunks(items, 7);

        return groups.map(function (group, index) {
            var first = index * 7 + 1;
            var last = first + group.length - 1;

            return {
                title: 'Сезоны ' + first + '–' + last,
                results: group,
                params: {
                    items: {
                        align_left: true,
                        view: 5
                    }
                }
            };
        });
    }

    function buildEpisodeLines(catalog, seasonNumber) {
        var season = seasonRecord(catalog, seasonNumber);

        if (!season || !season.episodes || !season.episodes.length) {
            return [{
                title: seasonNumber + ' сезон',
                results: [{
                    title: 'Каталог серий ещё не обновлён',
                    name: 'Каталог серий ещё не обновлён',
                    original_name: 'Запусти GitHub Action Update catalog',
                    overview: '',
                    kk_type: 'info',
                    params: {
                        style: {
                            name: 'wide'
                        }
                    }
                }]
            }];
        }

        var episodes = season.episodes
            .slice()
            .sort(function (a, b) {
                return parseInt(a.episode, 10) - parseInt(b.episode, 10);
            })
            .map(episodeCard);

        var groups = chunks(episodes, 8);

        return groups.map(function (group) {
            var firstEpisode = group[0].kk_episode.episode;
            var lastEpisode = group[group.length - 1].kk_episode.episode;

            return {
                title: group.length > 1
                    ? ('Серии ' + firstEpisode + '–' + lastEpisode)
                    : ('Серия ' + firstEpisode),
                results: group,
                params: {
                    items: {
                        align_left: true,
                        view: 4
                    }
                }
            };
        });
    }

    function NativeComponent(object) {
        var comp = Lampa.Maker.make('Main', object || {});
        var mode = (object && object.kk_mode) || 'seasons';
        var seasonNumber = parseInt(object && object.kk_season, 10) || 0;

        comp.use({
            onCreate: function () {
                var self = this;

                self.activity.loader(true);

                loadCatalog(function (catalog, fallback) {
                    self.activity.loader(false);

                    var lines = mode === 'episodes'
                        ? buildEpisodeLines(catalog, seasonNumber)
                        : buildSeasonLines(catalog);

                    self.build(lines);

                    if (fallback && mode === 'episodes') {
                        Lampa.Noty.show('catalog.json пока недоступен');
                    }
                });
            }        });

        return comp;
    }

    function openCatalog() {
        Lampa.Activity.push({
            component: COMPONENT,
            title: TITLE,
            kk_mode: 'seasons',
            page: 1
        });
    }

    function init() {
        if (typeof Lampa === 'undefined') {
            setTimeout(init, 300);
            return;
        }

        if (window[PLUGIN_ID + '_ready']) return;

        if (appDigital() < 300 || !Lampa.Maker) {
            Lampa.Noty.show('Плагину нужна Lampa 3.x');
            return;
        }

        window[PLUGIN_ID + '_ready'] = true;

        Lampa.Component.add(COMPONENT, NativeComponent);

        if (Lampa.Menu && Lampa.Menu.addButton) {
            Lampa.Menu.addButton(
                ICON,
                TITLE,
                openCatalog
            );
        }

        try {
            if (Lampa.Manifest && Lampa.Manifest.plugins) {
                Lampa.Manifest.plugins[PLUGIN_ID] = {
                    type: 'other',
                    version: VERSION,
                    name: TITLE,
                    description: 'Native Lampa.Maker UI + fixed action menu + GitHub catalog.json'
                };
            }
        } catch (e) {}
    }

    if (window.appready) {
        init();
    } else if (typeof Lampa !== 'undefined' && Lampa.Listener) {
        Lampa.Listener.follow('app', function (event) {
            if (event.type === 'ready') init();
        });
    } else {
        setTimeout(init, 500);
    }
})();
