/*
 * South Park / Kill Kenny catalog for Lampa 3.x
 * v2.1.0
 *
 * Architecture:
 *   custom cinematic carousel -> catalog.json on GitHub Pages
 *
 * catalog.json is generated by GitHub Actions from public metadata pages.
 * The browser/TV client never needs to fetch kill-kenny HTML directly.
 */
(function () {
    'use strict';

    var PLUGIN_ID = 'sp_killkenny_v1';
    var COMPONENT = 'sp_killkenny_native';
    var VERSION = '2.1.0';
    var TITLE = 'Южный Парк';
    var PROGRESS_PREFIX = 'kkv1_progress_';

    var SEASON_YEARS = {
        1: '1997',
        2: '1998',
        3: '1999',
        4: '2000',
        5: '2001',
        6: '2002',
        7: '2003',
        8: '2004',
        9: '2005',
        10: '2006',
        11: '2007',
        12: '2008',
        13: '2009',
        14: '2010',
        15: '2011',
        16: '2012',
        17: '2013',
        18: '2014',
        19: '2015',
        20: '2016',
        21: '2017',
        22: '2018',
        23: '2019',
        24: '2020–2021',
        25: '2022',
        26: '2023',
        27: '2025',
        28: '2025'
    };

    var SCRIPT_URL = (document.currentScript && document.currentScript.src) || '';
    var ASSET_BASE = SCRIPT_URL
        ? SCRIPT_URL.split('?')[0].replace(/[^/]+$/, '')
        : 'https://cloverdlae.github.io/sp-lampa/';

    var CATALOG_URLS = [
        ASSET_BASE + 'catalog.json?v=' + encodeURIComponent(VERSION),
        'https://raw.githubusercontent.com/cloverdlae/sp-lampa/main/catalog.json'
    ];

    /*
     * Known direct HLS rules supplied separately by the user.
     * Add only verified season rules here.
     */
    var STREAM_RULES = {
        1:  [{ id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s1-mtv/',        suffix: '.mp4/index.m3u8' }],
        2:  [{ id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s2-mtv/',        suffix: '.mp4/index.m3u8' }],
        3:  [{ id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s3-mtv/',        suffix: '.mp4/index.m3u8' }],
        4:  [{ id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s4-mtv/',        suffix: '.mp4/index.m3u8' }],
        5:  [{ id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s5-mtv/',        suffix: '.mp4/index.m3u8' }],
        6:  [{ id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s6-mtv/',        suffix: '.mp4/index.m3u8' }],
        7:  [{ id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s7-mtv/',        suffix: '.mp4/index.m3u8' }],
        8:  [{ id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s8-mtv/',        suffix: '.mp4/index.m3u8' }],
        9:  [{ id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s9-mtv/',        suffix: '.mp4/index.m3u8' }],
        10: [{ id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s10-mtv/',       suffix: '.mp4/index.m3u8' }],
        11: [{ id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s11-mtv/',       suffix: '.mp4/index.m3u8' }],
        12: [{ id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s12-mtv/',       suffix: '.mp4/index.m3u8' }],
        13: [{ id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s13-mtv/',       suffix: '.mp4/index.m3u8' }],

        14: [
            { id: 'mtv',       label: 'MTV',       base: 'https://cdn.videozcdn.uk/video/killkenny/s14-mtv/',       suffix: '.mp4/index.m3u8' },
            { id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/killkenny/s14-paramount/', suffix: '.mp4/index.m3u8' }
        ],

        15: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/killkenny/s15-paramount/', suffix: '.mp4/index.m3u8' }],
        16: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/killkenny/s16-paramount/', suffix: '.mp4/index.m3u8' }],
        17: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/killkenny/s17-paramount/', suffix: '.mp4/index.m3u8' }],
        18: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/killkenny/s18-paramount/', suffix: '.mp4/index.m3u8' }],
        19: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/killkenny/s19-paramount/', suffix: '.mp4/index.m3u8' }],
        20: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/killkenny/s20-paramount/', suffix: '.mp4/index.m3u8' }],
        21: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/killkenny/s21-paramount/', suffix: '.mp4/index.m3u8' }],
        22: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/killkenny/s22-paramount/', suffix: '.mp4/index.m3u8' }],
        23: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/killkenny/s23-paramount/', suffix: '.mp4/index.m3u8' }],
        24: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/killkenny/s24-paramount/', suffix: '.mp4/index.m3u8' }],

        25: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/spark/s25-paramount/', suffix: '.mp4/index.m3u8' }],
        26: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/spark/s26-paramount/', suffix: '.mp4/index.m3u8' }],
        27: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/spark/s27-paramount/', suffix: '.mp4/index.m3u8' }],
        28: [{ id: 'paramount', label: 'Paramount', base: 'https://cdn.videozcdn.uk/video/spark/s28-paramount/', suffix: '.mp4/index.m3u8' }]
    };

    var catalogCache = null;

    var ICON =
        '<svg viewBox="0 0 24 24" width="34" height="34" fill="none" stroke="currentColor" stroke-width="2">' +
            '<rect x="3" y="4" width="18" height="16" rx="2"></rect>' +
            '<path d="M7 8h10M7 12h10M7 16h6"></path>' +
        '</svg>';

    var CAROUSEL_STYLE_ID = 'kk-cinematic-carousel-style';

    function injectCarouselStyle() {
        if (document.getElementById(CAROUSEL_STYLE_ID)) return;

        var css = [
            '.kkc-root{position:relative;width:100%;height:100%;min-height:36em;overflow:hidden;isolation:isolate;user-select:none}',
            '.kkc-backdrop{position:absolute;inset:-8%;background-position:center;background-size:cover;filter:blur(3.5em) saturate(1.15);opacity:.16;transform:scale(1.12);transition:opacity .32s ease;z-index:0}',
            '.kkc-backdrop:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.32),rgba(0,0,0,.68) 72%,rgba(0,0,0,.88))}',
            '.kkc-vignette{position:absolute;inset:0;background:radial-gradient(ellipse at center,rgba(0,0,0,.02) 12%,rgba(0,0,0,.3) 57%,rgba(0,0,0,.7) 100%);z-index:1;pointer-events:none}',
            '.kkc-stage{position:relative;z-index:3;width:100%;height:100%;display:flex;flex-direction:column;justify-content:center;align-items:center;padding:1em 0 3.2em;box-sizing:border-box}',
            '.kkc-label{position:absolute;top:1.1em;left:2.1em;font-size:1.05em;letter-spacing:.1em;text-transform:uppercase;opacity:.48;font-weight:600}',
            '.kkc-counter{position:absolute;top:1.15em;right:2.2em;font-size:.95em;opacity:.42;font-variant-numeric:tabular-nums}',
            '.kkc-carousel{position:relative;width:100%;height:min(52vh,31em);min-height:21em;display:flex;align-items:center;justify-content:center;perspective:90em}',
            '.kkc-glow{position:absolute;left:50%;top:50%;width:min(51vw,49em);aspect-ratio:16/9;transform:translate(-50%,-48%) scale(1.04);background-position:center;background-size:cover;filter:blur(3.1em) saturate(1.5);opacity:.52;border-radius:2em;transition:background-image .18s ease,opacity .25s ease;pointer-events:none}',
            '.kkc-card{position:absolute;left:50%;top:50%;width:clamp(25em,43vw,46em);aspect-ratio:16/9;border-radius:1.05em;overflow:hidden;background:#171717;box-shadow:0 1.1em 3em rgba(0,0,0,.38);transform-origin:center center;transition:transform .36s cubic-bezier(.22,.75,.18,1),opacity .3s ease,filter .3s ease,box-shadow .3s ease;will-change:transform,opacity;cursor:pointer}',
            '.kkc-card__image{position:absolute;inset:0;background-size:cover;background-position:center;transform:scale(1.015);transition:transform .45s cubic-bezier(.22,.75,.18,1)}',
            '.kkc-card__shade{position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.03) 27%,rgba(0,0,0,.17) 52%,rgba(0,0,0,.88) 100%)}',
            '.kkc-card__content{position:absolute;left:1.7em;right:1.7em;bottom:1.45em;text-shadow:0 .08em .35em rgba(0,0,0,.78)}',
            '.kkc-card__title{font-size:2em;line-height:1.05;font-weight:650;letter-spacing:-.025em;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2;overflow:hidden}',
            '.kkc-card__meta{margin-top:.62em;font-size:1.02em;opacity:.72;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
            '.kkc-card__progress{position:absolute;left:0;right:0;bottom:0;height:.22em;background:rgba(255,255,255,.14);opacity:0}',
            '.kkc-card__progress span{display:block;height:100%;background:rgba(255,255,255,.82);width:0}',
            '.kkc-card.has-progress .kkc-card__progress{opacity:1}',
            '.kkc-card.is-active{box-shadow:0 1.6em 5em rgba(0,0,0,.58),0 0 0 .12em rgba(255,255,255,.92);filter:saturate(1.03) brightness(1.02)}',
            '.kkc-card.is-active .kkc-card__image{transform:scale(1.04)}',
            '.kkc-card.is-side{filter:saturate(.67) brightness(.64)}',
            '.kkc-card.is-far{filter:saturate(.45) brightness(.46)}',
            '.kkc-card.is-hidden{pointer-events:none}',
            '.kkc-card.focus.is-active{box-shadow:0 1.7em 5.6em rgba(0,0,0,.64),0 0 0 .15em rgba(255,255,255,1)}',
            '.kkc-footer{position:absolute;bottom:1.15em;left:50%;transform:translateX(-50%);display:flex;align-items:center;gap:1em;font-size:.9em;opacity:.35;white-space:nowrap}',
            '.kkc-arrow{font-size:1.35em;opacity:.75}',
            '@media (max-width:900px){.kkc-card{width:66vw}.kkc-carousel{height:46vh}.kkc-glow{width:70vw}.kkc-card__title{font-size:1.65em}}'
        ].join('');

        var style = document.createElement('style');
        style.id = CAROUSEL_STYLE_ID;
        style.textContent = css;
        document.head.appendChild(style);
    }

    function safeImage(url) {
        return String(url || '').replace(/"/g, '%22');
    }

    function mod(value, length) {
        if (!length) return 0;
        return ((value % length) + length) % length;
    }

    function circularDistance(index, active, length) {
        var distance = index - active;

        if (distance > length / 2) distance -= length;
        if (distance < -length / 2) distance += length;

        return distance;
    }

    function appDigital() {
        try {
            return Number(Lampa.Manifest.app_digital || 0);
        } catch (e) {
            return 0;
        }
    }

    function pad2(value) {
        value = parseInt(value, 10) || 0;
        return value < 10 ? ('0' + value) : String(value);
    }

    function streamSources(season) {
        return STREAM_RULES[parseInt(season, 10)] || [];
    }

    function streamRule(season, sourceId) {
        var sources = streamSources(season);

        if (!sources.length) return null;

        if (sourceId) {
            for (var i = 0; i < sources.length; i++) {
                if (sources[i].id === sourceId) return sources[i];
            }
        }

        return sources[0];
    }

    function streamUrl(season, episode, sourceId) {
        var rule = streamRule(season, sourceId);

        if (!rule) return '';

        return rule.base + pad2(episode) + rule.suffix;
    }


    function progressKey(episode) {
        return PROGRESS_PREFIX + 's' + pad2(episode.season) + 'e' + pad2(episode.episode);
    }

    function normalizeProgress(value) {
        value = value && typeof value === 'object' ? value : {};

        var time = parseFloat(value.time || 0);
        var duration = parseFloat(value.duration || 0);
        var percent = parseFloat(value.percent || 0);

        if (!isFinite(time) || time < 0) time = 0;
        if (!isFinite(duration) || duration < 0) duration = 0;

        if ((!isFinite(percent) || percent < 0) && duration > 0) {
            percent = Math.round(time / duration * 100);
        }

        if (!isFinite(percent) || percent < 0) percent = 0;
        if (percent > 100) percent = 100;

        return {
            time: time,
            duration: duration,
            percent: percent,
            updated_at: value.updated_at || 0
        };
    }

    function readProgress(episode) {
        try {
            return normalizeProgress(Lampa.Storage.get(progressKey(episode), {}));
        } catch (e) {
            return normalizeProgress({});
        }
    }

    function saveProgress(episode, percent, time, duration) {
        var data = normalizeProgress({
            percent: percent,
            time: time,
            duration: duration,
            updated_at: Date.now()
        });

        try {
            Lampa.Storage.set(progressKey(episode), data);
        } catch (e) {}

        return data;
    }

    function clearProgress(episode) {
        try {
            Lampa.Storage.set(progressKey(episode), {
                percent: 0,
                time: 0,
                duration: 0,
                updated_at: Date.now()
            });
        } catch (e) {}
    }

    function timelineForEpisode(episode, restart) {
        var saved = restart ? normalizeProgress({}) : readProgress(episode);

        return {
            percent: saved.percent,
            time: saved.time,
            duration: saved.duration,
            handler: function (percent, time, duration) {
                saveProgress(episode, percent, time, duration);
            }
        };
    }

    function formatTime(seconds) {
        seconds = Math.max(0, Math.floor(parseFloat(seconds || 0)));

        var hours = Math.floor(seconds / 3600);
        var minutes = Math.floor((seconds % 3600) / 60);
        var secs = seconds % 60;

        function two(value) {
            return value < 10 ? ('0' + value) : String(value);
        }

        return hours
            ? (hours + ':' + two(minutes) + ':' + two(secs))
            : (minutes + ':' + two(secs));
    }

    function progressLabel(episode) {
        var progress = readProgress(episode);

        if (progress.percent >= 90) {
            return {
                type: 'watched',
                text: '✓ просмотрено',
                progress: progress
            };
        }

        if (progress.time > 10) {
            return {
                type: 'continue',
                text: '▶ продолжить с ' + formatTime(progress.time),
                progress: progress
            };
        }

        return {
            type: 'new',
            text: '▶ OK — смотреть',
            progress: progress
        };
    }

    function fallbackCatalog() {
        var seasons = {};

        for (var i = 1; i <= 28; i++) {
            seasons[String(i)] = {
                season: i,
                title: i + ' сезон',
                episodes: []
            };
        }

        return {
            version: 1,
            source: 'kill-kenny.com',
            updated_at: null,
            seasons: seasons
        };
    }

    function parseCatalog(text) {
        var data = typeof text === 'string' ? JSON.parse(text) : text;

        if (!data || typeof data !== 'object') throw new Error('bad catalog');
        if (!data.seasons || typeof data.seasons !== 'object') throw new Error('no seasons');

        return data;
    }

    function loadText(url, success, fail) {
        if (typeof fetch === 'function') {
            fetch(url, {
                method: 'GET',
                mode: 'cors',
                cache: 'no-store'
            })
            .then(function (response) {
                if (!response.ok) throw new Error('HTTP ' + response.status);
                return response.text();
            })
            .then(success)
            .catch(function () {
                requestFallback(url, success, fail);
            });

            return;
        }

        requestFallback(url, success, fail);
    }

    function requestFallback(url, success, fail) {
        try {
            var network = Lampa.Network
                ? new Lampa.Network()
                : new Lampa.Reguest();

            network.silent(
                url,
                function (data) {
                    success(typeof data === 'string' ? data : String(data || ''));
                },
                fail,
                false,
                {
                    dataType: 'text',
                    cache: {
                        life: 5
                    }
                }
            );
        } catch (e) {
            fail(e);
        }
    }

    function loadCatalog(done) {
        if (catalogCache) {
            done(catalogCache, false);
            return;
        }

        var index = 0;

        function next() {
            if (index >= CATALOG_URLS.length) {
                catalogCache = fallbackCatalog();
                done(catalogCache, true);
                return;
            }

            var url = CATALOG_URLS[index++];

            loadText(
                url,
                function (text) {
                    try {
                        catalogCache = parseCatalog(text);
                        done(catalogCache, false);
                    } catch (e) {
                        next();
                    }
                },
                next
            );
        }

        next();
    }

    function seasonRecord(catalog, season) {
        return catalog &&
            catalog.seasons &&
            (catalog.seasons[String(season)] || catalog.seasons[season]);
    }

    function firstPoster(seasonData) {
        if (!seasonData || !seasonData.episodes) return '';

        for (var i = 0; i < seasonData.episodes.length; i++) {
            if (seasonData.episodes[i].poster) return seasonData.episodes[i].poster;
        }

        return '';
    }

    function chunks(items, size) {
        var out = [];

        for (var i = 0; i < items.length; i += size) {
            out.push(items.slice(i, i + size));
        }

        return out;
    }

    function seasonCarouselItem(seasonData) {
        var season = parseInt(seasonData.season, 10) || 0;

        return {
            type: 'season',
            season: season,
            title: season + ' сезон',
            meta: SEASON_YEARS[season] || '',
            image: firstPoster(seasonData),
            seasonData: seasonData
        };
    }

    function episodeCarouselItem(episode) {
        var state = progressLabel(episode);
        var meta = episode.episode + ' серия';

        if (state.type === 'continue') {
            meta += '  •  продолжить с ' + formatTime(state.progress.time);
        } else if (state.type === 'watched') {
            meta += '  •  просмотрено';
        }

        return {
            type: 'episode',
            season: episode.season,
            episode: episode.episode,
            title: episode.title || (episode.episode + ' серия'),
            meta: meta,
            image: episode.poster || '',
            progress: state.progress,
            episodeData: episode
        };
    }

    function carouselInitialIndex(mode, season, items) {
        if (!items.length) return 0;

        try {
            if (mode === 'seasons') {
                var savedSeason = parseInt(Lampa.Storage.get('kkc_last_season', 1), 10) || 1;

                for (var i = 0; i < items.length; i++) {
                    if (items[i].season === savedSeason) return i;
                }
            } else {
                var key = 'kkc_last_episode_s' + season;
                var savedEpisode = parseInt(Lampa.Storage.get(key, 1), 10) || 1;

                for (var j = 0; j < items.length; j++) {
                    if (items[j].episode === savedEpisode) return j;
                }
            }
        } catch (e) {}

        return 0;
    }

    function rememberCarouselItem(item) {
        if (!item) return;

        try {
            if (item.type === 'season') {
                Lampa.Storage.set('kkc_last_season', item.season);
            } else {
                Lampa.Storage.set('kkc_last_episode_s' + item.season, item.episode);
            }
        } catch (e) {}
    }

    function CinematicCarouselComponent(object) {
        var self = this;
        var mode = (object && object.kk_mode) || 'seasons';
        var seasonNumber = parseInt(object && object.kk_season, 10) || 0;
        var controllerName = 'content';
        var items = [];
        var logicalCount = 0;
        var cards = [];
        var activeIndex = 0;
        var ready = false;
        var wheelLock = false;
        var touchStartX = 0;
        var resizeTimer = null;

        injectCarouselStyle();

        var root = $(
            '<div class="kkc-root">' +
                '<div class="kkc-backdrop"></div>' +
                '<div class="kkc-vignette"></div>' +
                '<div class="kkc-stage">' +
                    '<div class="kkc-label"></div>' +
                    '<div class="kkc-counter"></div>' +
                    '<div class="kkc-carousel">' +
                        '<div class="kkc-glow"></div>' +
                        '<div class="kkc-track"></div>' +
                    '</div>' +
                    '<div class="kkc-footer">' +
                        '<span class="kkc-arrow">‹</span>' +
                        '<span>листать</span>' +
                        '<span>OK — выбрать</span>' +
                        '<span class="kkc-arrow">›</span>' +
                    '</div>' +
                '</div>' +
            '</div>'
        );

        var backdrop = root.find('.kkc-backdrop');
        var glow = root.find('.kkc-glow');
        var track = root.find('.kkc-track');
        var label = root.find('.kkc-label');
        var counter = root.find('.kkc-counter');

        function safeAction(action) {
            try {
                return action();
            } catch (error) {
                try {
                    console.error('[KillKenny v2.1]', error);
                } catch (consoleError) {}

                try {
                    Lampa.Noty.show(
                        'Ошибка интерфейса: ' +
                        (error && error.message ? error.message : String(error))
                    );
                } catch (notyError) {}

                return null;
            }
        }

        function activeItem() {
            return items.length ? items[activeIndex] : null;
        }

        function cardProgress(item) {
            if (!item || item.type !== 'episode' || !item.progress) return 0;

            var percent = parseFloat(item.progress.percent || 0);

            if (!isFinite(percent) || percent <= 0) return 0;
            if (percent > 100) percent = 100;

            return percent;
        }

        function makeCard(item, index) {
            var element = $(
                '<div class="kkc-card">' +
                    '<div class="kkc-card__image"></div>' +
                    '<div class="kkc-card__shade"></div>' +
                    '<div class="kkc-card__content">' +
                        '<div class="kkc-card__title"></div>' +
                        '<div class="kkc-card__meta"></div>' +
                    '</div>' +
                    '<div class="kkc-card__progress"><span></span></div>' +
                '</div>'
            );

            element.attr('data-index', index);
            element.find('.kkc-card__title').text(item.title || '');
            element.find('.kkc-card__meta').text(item.meta || '');

            if (item.image) {
                element.find('.kkc-card__image').css(
                    'background-image',
                    'url("' + safeImage(item.image) + '")'
                );
            }

            var progress = cardProgress(item);

            if (progress > 0) {
                element.addClass('has-progress');
                element.find('.kkc-card__progress span').css('width', progress + '%');
            }

            element.on('mouseenter.kkc', function () {
                var target = parseInt($(this).attr('data-index'), 10);

                if (target !== activeIndex) {
                    safeAction(function () {
                        setActive(target, true);
                    });
                }
            });

            element.on('click.kkc', function (event) {
                event.preventDefault();
                event.stopPropagation();

                var target = parseInt($(this).attr('data-index'), 10);

                safeAction(function () {
                    if (target !== activeIndex) {
                        setActive(target, true);
                        return;
                    }

                    activateCurrent();
                });
            });

            track.append(element);
            return element;
        }

        function spacing() {
            var width = root.width() || window.innerWidth || 1280;
            return Math.min(650, Math.max(330, width * 0.335));
        }

        function renderPositions(animate) {
            if (!items.length) return;

            var gap = spacing();

            cards.forEach(function (element, index) {
                var distance = circularDistance(index, activeIndex, items.length);
                var absolute = Math.abs(distance);

                element
                    .removeClass('is-active is-side is-far is-hidden focus')
                    .css('transition-duration', animate ? '' : '0s');

                if (absolute > 2) {
                    element
                        .addClass('is-hidden')
                        .css({
                            opacity: 0,
                            zIndex: 0,
                            pointerEvents: 'none',
                            transform:
                                'translate3d(calc(-50% + ' +
                                (distance < 0 ? -gap * 2.35 : gap * 2.35) +
                                'px),-50%,0) scale(.55)'
                        });
                    return;
                }

                var scale = absolute === 0 ? 1 : (absolute === 1 ? .78 : .62);
                var opacity = absolute === 0 ? 1 : (absolute === 1 ? .56 : .22);
                var x = distance * gap;
                var z = absolute === 0 ? 30 : (absolute === 1 ? 20 : 10);

                element
                    .toggleClass('is-active', absolute === 0)
                    .toggleClass('is-side', absolute === 1)
                    .toggleClass('is-far', absolute === 2)
                    .css({
                        opacity: opacity,
                        zIndex: z,
                        pointerEvents: absolute <= 2 ? 'auto' : 'none',
                        transform:
                            'translate3d(calc(-50% + ' +
                            x +
                            'px),-50%,0) scale(' +
                            scale +
                            ')'
                    });
            });

            if (!animate) {
                setTimeout(function () {
                    cards.forEach(function (element) {
                        element.css('transition-duration', '');
                    });
                }, 20);
            }
        }

        function renderAtmosphere() {
            var item = activeItem();
            if (!item) return;

            var logicalIndex = item._logicalIndex !== undefined ? item._logicalIndex : activeIndex;
            counter.text((logicalIndex + 1) + ' / ' + (logicalCount || items.length));

            var image = item.image || '';

            if (image) {
                var imageCss = 'url("' + safeImage(image) + '")';

                glow.css('background-image', imageCss);
                backdrop.css('background-image', imageCss);

                try {
                    Lampa.Background.change(image);
                } catch (e) {}
            } else {
                glow.css('background-image', 'none');
                backdrop.css('background-image', 'none');
            }
        }

        function focusActive() {
            if (!cards.length) return;

            cards.forEach(function (element) {
                element.removeClass('focus');
            });

            var current = cards[activeIndex];

            if (current) {
                current.addClass('focus');
            }
        }

        function setActive(index, animate) {
            if (!items.length) return;

            activeIndex = mod(index, items.length);

            rememberCarouselItem(activeItem());
            renderPositions(animate !== false);
            renderAtmosphere();
            focusActive();
        }

        function move(direction) {
            if (!ready || !items.length) return;

            safeAction(function () {
                setActive(activeIndex + direction, true);
            });
        }

        function activateCurrent() {
            var item = activeItem();
            if (!item) return;

            rememberCarouselItem(item);

            if (item.type === 'season') {
                pushSeason(item.season);
                return;
            }

            if (item.type === 'episode' && item.episodeData) {
                openEpisodeActions(item.episodeData);
            }
        }

        function buildFromCatalog(catalog) {
            items = [];

            if (mode === 'seasons') {
                label.text('Сезоны');

                Object.keys(catalog.seasons || {})
                    .map(function (key) {
                        return seasonRecord(catalog, parseInt(key, 10));
                    })
                    .filter(Boolean)
                    .sort(function (a, b) {
                        return parseInt(a.season, 10) - parseInt(b.season, 10);
                    })
                    .forEach(function (seasonData) {
                        items.push(seasonCarouselItem(seasonData));
                    });
            } else {
                label.text(seasonNumber + ' сезон');

                var season = seasonRecord(catalog, seasonNumber);

                if (season && season.episodes) {
                    season.episodes
                        .slice()
                        .sort(function (a, b) {
                            return parseInt(a.episode, 10) - parseInt(b.episode, 10);
                        })
                        .forEach(function (episode) {
                            items.push(episodeCarouselItem(episode));
                        });
                }
            }

            logicalCount = items.length;

            // Для коротких сезонов (например, сезон 24) визуально повторяем
            // элементы вокруг центра. Логическая последовательность всё равно
            // остаётся исходной: E1 → E2 → E1 → E2 ...
            if (mode === 'episodes' && items.length > 0 && items.length < 5) {
                var logicalItems = items.slice();
                var expanded = [];
                var expandedLength = Math.max(6, logicalItems.length * 3);

                for (var repeatIndex = 0; repeatIndex < expandedLength; repeatIndex++) {
                    var original = logicalItems[repeatIndex % logicalItems.length];
                    var clone = {};

                    Object.keys(original).forEach(function (key) {
                        clone[key] = original[key];
                    });

                    clone._logicalIndex = repeatIndex % logicalItems.length;
                    expanded.push(clone);
                }

                items = expanded;
            }

            track.empty();
            cards = [];

            items.forEach(function (item, index) {
                cards.push(makeCard(item, index));
            });

            if (!items.length) {
                label.text(mode === 'seasons' ? 'Сезоны' : seasonNumber + ' сезон');
                counter.text('');
                track.append(
                    $('<div style="position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);opacity:.55;font-size:1.1em"></div>')
                        .text('Каталог пока пуст')
                );
                return;
            }

            activeIndex = carouselInitialIndex(mode, seasonNumber, items);

            if (mode === 'episodes' && logicalCount > 0 && logicalCount < 5) {
                var wanted = items[activeIndex] && items[activeIndex]._logicalIndex !== undefined
                    ? items[activeIndex]._logicalIndex
                    : 0;
                var middle = Math.floor(items.length / 2);
                var best = activeIndex;
                var bestDistance = Infinity;

                items.forEach(function (candidate, candidateIndex) {
                    if (candidate._logicalIndex !== wanted) return;

                    var distanceToMiddle = Math.abs(candidateIndex - middle);
                    if (distanceToMiddle < bestDistance) {
                        bestDistance = distanceToMiddle;
                        best = candidateIndex;
                    }
                });

                activeIndex = best;
            }

            ready = true;

            renderPositions(false);
            renderAtmosphere();
            focusActive();
        }

        function bindPointerNavigation() {
            root.on('wheel.kkc', function (event) {
                if (!ready || wheelLock) return;

                var original = event.originalEvent || event;
                var delta = Math.abs(original.deltaX || 0) > Math.abs(original.deltaY || 0)
                    ? original.deltaX
                    : original.deltaY;

                if (Math.abs(delta || 0) < 8) return;

                event.preventDefault();
                wheelLock = true;
                move(delta > 0 ? 1 : -1);

                setTimeout(function () {
                    wheelLock = false;
                }, 180);
            });

            root.on('touchstart.kkc pointerdown.kkc', function (event) {
                var original = event.originalEvent || event;
                var point = original.touches && original.touches[0]
                    ? original.touches[0]
                    : original;

                touchStartX = Number(point.clientX || 0);
            });

            root.on('touchend.kkc pointerup.kkc', function (event) {
                var original = event.originalEvent || event;
                var point = original.changedTouches && original.changedTouches[0]
                    ? original.changedTouches[0]
                    : original;

                var endX = Number(point.clientX || 0);
                var diff = endX - touchStartX;

                if (Math.abs(diff) > 55) {
                    move(diff < 0 ? 1 : -1);
                }
            });
        }

        this.create = function () {
            this.activity.loader(true);

            bindPointerNavigation();

            loadCatalog(function (catalog, fallback) {
                safeAction(function () {
                    if (!root || !root.length || !document.documentElement.contains(root[0])) {
                        return;
                    }

                    self.activity.loader(false);
                    buildFromCatalog(catalog);

                    if (fallback && mode === 'episodes') {
                        Lampa.Noty.show('catalog.json пока недоступен');
                    }
                });
            });

            return this.render();
        };

        this.render = function () {
            return root;
        };

        this.start = function () {
            Lampa.Controller.add(controllerName, {
                toggle: function () {
                    safeAction(function () {
                        focusActive();
                    });
                },
                left: function () {
                    move(-1);
                },
                right: function () {
                    move(1);
                },
                up: function () {
                    safeAction(function () {
                        Lampa.Controller.toggle('head');
                    });
                },
                down: function () {},
                enter: function () {
                    safeAction(function () {
                        activateCurrent();
                    });
                },
                back: function () {
                    safeAction(function () {
                        self.back();
                    });
                }
            });

            Lampa.Controller.toggle(controllerName);
        };

        this.pause = function () {};
        this.stop = function () {};

        this.back = function () {
            Lampa.Activity.backward();
        };

        this.destroy = function () {
            root.off('.kkc');

            cards.forEach(function (element) {
                try {
                    element.off('.kkc');
                } catch (e) {}
            });

            if (resizeTimer) clearTimeout(resizeTimer);

            $(window).off('resize.kkc');

            root.remove();
        };

        $(window).on('resize.kkc', function () {
            clearTimeout(resizeTimer);
            resizeTimer = setTimeout(function () {
                renderPositions(false);
            }, 100);
        });
    }

    function openCatalog() {
        Lampa.Activity.push({
            component: COMPONENT,
            title: TITLE,
            kk_mode: 'seasons',
            page: 1
        });
    }

    function init() {
        if (typeof Lampa === 'undefined') {
            setTimeout(init, 300);
            return;
        }

        if (window[PLUGIN_ID + '_ready']) return;

        if (appDigital() < 300) {
            Lampa.Noty.show('Плагину нужна Lampa 3.x');
            return;
        }

        window[PLUGIN_ID + '_ready'] = true;

        Lampa.Component.add(COMPONENT, CinematicCarouselComponent);

        if (Lampa.Menu && Lampa.Menu.addButton) {
            Lampa.Menu.addButton(
                ICON,
                TITLE,
                openCatalog
            );
        }

        try {
            if (Lampa.Manifest && Lampa.Manifest.plugins) {
                Lampa.Manifest.plugins[PLUGIN_ID] = {
                    type: 'other',
                    version: VERSION,
                    name: TITLE,
                    description: 'Cinematic 16:9 carousel v2.1 + isolated input + HLS + resume'
                };
            }
        } catch (e) {}
    }

    if (window.appready) {
        init();
    } else if (typeof Lampa !== 'undefined' && Lampa.Listener) {
        Lampa.Listener.follow('app', function (event) {
            if (event.type === 'ready') init();
        });
    } else {
        setTimeout(init, 500);
    }
})();
